name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  setup-docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build and tag the Docker image
        run: docker build . --tag ghcr.io/mmafrar/alpine-react-native-android:latest
      - name: Push the Docker image to the registry
        run: docker push ghcr.io/mmafrar/alpine-react-native-android:latest
